### ISSUE TITLE
Some questions in the utils.py

### ISSUE THREAD

**Issue by Zhangwenbo0324** [mtoneva/brain_language_nlp#1]
I have two questions about the utils.py.
1.
   In the script located in ./utils/utils.py, the following codes in **def run_class_time_CV_fmri_crossval_ridge** is to skip TRs between train and test data. Could you please tell me why we should do this skip?
```
#skip TRs between train and test data
if ind_num == 0: # just remove from front end
    train_data = train_data[skip:,:]
    train_features = train_features[skip:,:]
elif ind_num == n_folds-1: # just remove from back end
    train_data = train_data[:-skip,:]
    train_features = train_features[:-skip,:]
else:
    train_data = train_data[skip:-skip,:]
    train_features = train_features[skip:-skip,:]

```
2.
    In the script located in ./utils/utils.py, the following is some codes in the function **def prepare_fmri_features**:
```
#w=find what TR each word belongs to
for i in range(len(time_words)):
    words_id[i] = np.where(time_words[i]> time)[0][-1]
    
all_features = np.zeros([time_words.shape[0], train_features.shape[1]])
all_features[word_train_indicator] = train_features
all_features[~word_train_indicator] = test_features
    
p = all_features.shape[1]
tmp = np.zeros([time.shape[0], p])
for i in range(time.shape[0]):
    tmp[i] = np.mean(all_features[(words_id<=i)*(words_id>=i-1)],0)
tmp = delay_mat(tmp, np.arange(1,5))
```
Among this codes, the line `tmp[i] = np.mean(all_features[(words_id<=i)*(words_id>=i-1)],0)` may make some mistakes. This would average the 8 words in 2 TRs. However we should have averaged the 4 words in a single TR.

**Comment by mtoneva** [comment]
Regarding 1: in order to account for the lag in the hemodynamic response from fMRI recordings, each brain image (TR)'s corresponding NLP features are computed as a function of the words that appear in the previous 4 TRs.  So we remove 5 TRs between the train and test data to be extra careful that no TR's corresponding NLP features (resulting from the function `prepare_fmri_features`) appear in both the train and test features. The else statement in the code excerpt should say `test_data = test_data[skip:-skip,:]` and `test_features = test_features[skip:-skip,:]`, which I've corrected in the code.

Regarding 2: thanks for pointing this out. You're right -- `words_id>=i-1` should be `words_id>i-1`. I've made the corresponding change in the code.

**Comment by nikitas-theo** [comment]
Hello, are you sure the code fix is correct? Because with the new code I get the following error : 
 `in run_class_time_CV_fmri_crossval_ridge
ValueError: shape mismatch: value array of shape (292,27905) could not be broadcast to indexing result of shape (302,27905)
`
at the command `        preds_d[test_ind] = preds`

And the problem seems to be that test_features now has shape 292 but test_ind is set to 302 at the start of the loop        `test_ind = ind==ind_num`

**Comment by mtoneva** [comment]
Thanks for pointing this out. The code fix is correct but it was also necessary to change the way that the predictions are being aggregated over the cross-validation folds (as they are now of different dimensions). I've added this fix and the code runs through without errors and produces expected results.
